import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "tienda | admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-poppins text-dark text-sm leading-loose`}>
        {children}
      </body>
    </html>
  );
}
