import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { TopMenu } from "@/components";
import NavMenu from "@/components/ui/top-menu/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-poppins text-dark text-sm leading-loose`}>
        <TopMenu></TopMenu>
        <NavMenu></NavMenu>
        <main>{children}</main>
      </body>
    </html>
  );
}
